import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

import { useState } from "react";

function CountdownItem({ id, name, onDelete }) {
  const [confirmDelete, setConfirmDelete] = useState(false);

    return (
        <div className="relative border p-4 rounded-xl shadow-md flex justify-between items-center">
              <div>
                      <p className="text-lg font-semibold">{name}</p>
                            </div>
                                  <div className="flex gap-2 items-center">
                                          <button className="text-blue-500 hover:underline" onClick={() => window.open(`/countdown/${id}`, "_blank")}>
                                                    Otwórz
                                                            </button>
                                                                    <button className="text-red-500" onClick={() => setConfirmDelete(true)}>
                                                                              🗑️
                                                                                      </button>
                                                                                            </div>

                                                                                                  {confirmDelete && (
                                                                                                          <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center z-10">
                                                                                                                    <div className="bg-white p-6 rounded-xl shadow-lg text-center space-y-4 max-w-sm w-full">
                                                                                                                                <p className="text-lg font-bold">Czy na pewno chcesz usunąć ten licznik?</p>
                                                                                                                                            <div className="flex justify-around">
                                                                                                                                                          <button
                                                                                                                                                                          className="bg-gray-300 hover:bg-gray-400 text-black px-4 py-2 rounded-lg"
                                                                                                                                                                                          onClick={() => setConfirmDelete(false)}
                                                                                                                                                                                                        >
                                                                                                                                                                                                                        Anuluj
                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                    className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg"
                                                                                                                                                                                                                                                                                    onClick={() => {
                                                                                                                                                                                                                                                                                                      onDelete(id);
                                                                                                                                                                                                                                                                                                                        setConfirmDelete(false);
                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                      Tak, usuń
                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                              function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                const handleDelete = (id) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                  alert(`Usunięto licznik o ID: ${id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold mb-4">Moje liczniki</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <CountdownItem id="abc123" name="Licznik testowy" onDelete={handleDelete} />
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;

